module.exports = {
  BUCKET_CONFIG: "convert.tapdone.com-configs",
  BUCKET_TEMP: "convert.tapdone.com-temp",
  BUCKET_INCOMING: "convert.tapdone.com-incoming",
  CONFIG_FILE_SUFFIX: ".settings.json",
  TEMPLATE_FILE_SUFFIX: ".template.pug",
  DEFAULT_API_KEY: "default",
  API_KEY_HEADER_NAME: "apiKey",
  SENTRY_DNS: "https://20998950600943508cd693e57edbe610@sentry.io/1788523",
  API_PRE_CHECK: "/pdfconvert_precheck",
  API_CONVERT: "/pdfconvert_convert_pdf",
  API_SEND_PDF: "/pdfconvert_send_pdf",
  API_URL: "https://0raxo3dqv1.execute-api.us-west-2.amazonaws.com/latest",
  //API_URL: "http://localhost:3000",
  SES_SMTP_SRV: 'email-smtp.us-west-2.amazonaws.com',
  SES_SMTP_PORT: 465,
  SES_SMTP_SSL: true,
  SES_SMTP_USER: 'AKIA57WK4KL4URZBRZPJ',
  SES_SMTP_PASS: 'BKieUH24d2EoWerUGshqYIxCun0HvqVGpmgh9WqBxaPk',
  SES_FROM: 'pdf@convert.tapdone.com',
  SES_DOMAIN: 'convert.tapdone.com',
  BUILD_TIME: "[2019-11-29 09:00]"
}